name: Test-Other
on:
  workflow_call:
jobs:
  qualif:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v1
    - name: Run custom action
      # Use the location in the repository (without action.yml)
      uses: ./.github/actions/setup
      with:
        install-chaos: false
    - name: deploy openldap-stack-ha-disable-ldap-port
      shell: bash
      run: |
        cd "$GITHUB_WORKSPACE"
        helm install openldap-stack-ha -n no-ldap-port --create-namespace -f .bin/disableLdapPort.yaml .
        kubectl -n no-ldap-port rollout status sts openldap-stack-ha -n no-ldap-port
    - name: verify no ldap port deployment
      shell: bash
      run: |
          echo "test access to openldap database"
          echo "Write test to openldap database"
          LDAPTLS_REQCERT=never ldapadd -x -D 'cn=admin,dc=example,dc=org' -w Not@SecurePassw0rd -H ldaps://localhost:30636 -f .bin/simpleUser.ldif
          LDAPTLS_REQCERT=never ldapsearch -o nettimeout=20 -x -D 'cn=admin,dc=example,dc=org' -w Not@SecurePassw0rd -H ldaps://localhost:30636 -b 'dc=example,dc=org' > /tmp/test-write.txt
          cat /tmp/test-write.txt
          if [ $(grep "numResponses" /tmp/test-write.txt | cut -d ":" -f 2 | tr -d ' ') -ne 3 ]; then exit 1 ; fi


      
