name: Test-SingleNode
on:
  workflow_call:
jobs:
  qualif:
      runs-on: ubuntu-latest
      steps:
      - name: Check out code
        uses: actions/checkout@v1
      - name: Run custom action
        # Use the location in the repository (without action.yml)
        uses: ./.github/actions/setup
        with:
          install-chaos: false
      - name: deploy openldap-stack-ha-single-node
        shell: bash
        run: |
          cd "$GITHUB_WORKSPACE"
          kubectl create ns single
          kubectl create secret generic my-super-secret -n single --from-literal=LDAP_ADMIN_PASSWORD=Not@SecurePassw0rd --from-literal=LDAP_CONFIG_ADMIN_PASSWORD=Not@SecurePassw0rd
          helm install openldap-stack-ha -n single -f .bin/singleNode.yaml .
          kubectl rollout status sts openldap-stack-ha -n single
          kubectl logs -n single openldap-stack-ha-0  
      - name: verify single node deployment
        shell: bash
        run: |
           sleep 10
           echo "test access to openldap database"
           LDAPTLS_REQCERT=never ldapsearch -x -D 'cn=admin,dc=singlenode,dc=org' -w Not@SecurePassw0rd -H ldaps://localhost:30636 -b 'dc=singlenode,dc=org' > /tmp/test-single-node.txt
           cat /tmp/test-single-node.txt
           if [ $(grep "numResponses" /tmp/test-single-node.txt | cut -d ":" -f 2 | tr -d ' ') -ne 6 ]; then exit 1 ; fi